apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring2
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 7.3.8
    chart: grafana
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  